### ISSUE TITLE
Lab1 solution cannot work

### ISSUE THREAD

**Issue by skyler-max** [digital-asset/certification-damlfundamentals-testingindaml-lab-solution#1]
I copy the code of Lab1, and Main under a project but got an error. Same thing happened when using the code in "Navigator" course.
How to deal with this?

![image](https://github.com/digital-asset/certification-damlfundamentals-testingindaml-lab-solution/assets/74391022/4b85f76f-cd6c-4c5e-a8c7-35159d79104d)

**Comment by alexputkov-da** [comment]
Up until Daml SDK v2.5.0 the function validateUserId required all lower case input. It seems you're using Daml SDK version earlier than 2.5.0. The simple solution is to bump up the version of Daml SDK in daml.yaml file in your project. You’ll need to save the daml.yaml file and restart VS Code for the change to take effect. Or, instead of copying and pasting modules from the repo into your own project, you can clone the repo from Github. The repo includes daml.yaml file that specifies the version of Daml SDK, that the project was created with, as v2.6.1.
